### ISSUE TITLE
updated level 1 data flow diagram

### ISSUE THREAD

**Issue by benmwilson** [benmwilson/dicomanon#19]
need to make an updated dfd lvl 1 based on the prof's comments below

> I did not understand the DFD level 0. What are the external entities of the system? I also noticed all the data flows into the same direction, is this correct in your system? Is the server a database external or internal to your system? If the database is a solution of your system, you do not have to include it in the DFD level 0. Please check this (https://blog.hubspot.com/marketing/data-flow-diagram) to improve your DFD level 0. Also, you mention that the researchers can query the database, but there is no “query data” from the researches to the server in the DFD.

**Comment by yiduguo-hp** [comment]
Added revised DFD diagram
